// 戦型 / 囲い / 作戦 classifier.
//
// Rules live in rules.json, generated by tools/convert-classifier-rules.py from
// tayayan/HiraganaSuisho tac_match.py (MIT, (c) 2023 tayayan) and
// mizar/sylwi-kifu-vue castle.yaml (MIT, (c) 2020 Mizar). The matching
// semantics follow tac_match.py: castles are re-evaluated after each of the
// side's moves (first hit in priority order wins, changes form a timeline),
// 戦型 lock on the first hit, 作戦 accumulate.
import rulesJson from "./rules.json" with { type: "json" };

export type RuleExpr =
  | { all: string }
  | { any: string }
  | { empty: string }
  | { and: RuleExpr[] }
  | { or: RuleExpr[] }
  | { not: RuleExpr };

export type RuleGroup = "castle" | "opening" | "opening_side" | "tactic_black" | "tactic_white" | "tactic";

export type Rule = {
  id: string;
  name: string;
  group: RuleGroup;
  view: "self" | "absolute";
  priority: number;
  plyMax?: number;
  expr: RuleExpr;
  source: string;
};

export type Side = "black" | "white";
export type Labelled = { name: string; ply: number };

export type Classification = {
  /** Symmetric 戦型 such as 角換わり / 相掛かり / 相振り飛車. */
  opening: Labelled | null;
  /** Per-side 戦型 such as 四間飛車 when no symmetric one was found first. */
  sideOpening: Record<Side, Labelled | null>;
  /** 居飛車 or 振り飛車 for each side, from the rook's file in the opening. */
  style: Record<Side, "居飛車" | "振り飛車">;
  castles: Record<Side, Labelled[]>;
  /** The castle the side settled in: last change within the first 60 plies. */
  mainCastle: Record<Side, string>;
  tactics: Record<Side, Labelled[]>;
};

type Cell = string; // "" | "P" | "+B" | "k" ...
type Hand = Record<string, number>;
type Board = { cells: Cell[]; hand: Hand };

function parseBoard(sfenBoard: string): Cell[] {
  const cells: Cell[] = [];
  let promoted = false;
  for (const ch of sfenBoard) {
    if (ch === "/") continue;
    if (ch === "+") {
      promoted = true;
      continue;
    }
    if (ch >= "1" && ch <= "9") {
      for (let i = 0; i < Number(ch); i++) cells.push("");
      continue;
    }
    cells.push(promoted ? "+" + ch : ch);
    promoted = false;
  }
  if (cells.length !== 81) throw new Error(`bad sfen board: ${sfenBoard}`);
  return cells;
}

function parseHand(text: string | undefined): Hand {
  const hand: Hand = {};
  if (!text || text === "-") return hand;
  let n = "";
  for (const ch of text) {
    if (ch >= "0" && ch <= "9") {
      n += ch;
      continue;
    }
    hand[ch] = (hand[ch] ?? 0) + (n ? Number(n) : 1);
    n = "";
  }
  return hand;
}

function swapCase(p: string): string {
  return p.replace(/[a-zA-Z]/, (c) => (c === c.toUpperCase() ? c.toLowerCase() : c.toUpperCase()));
}

export function boardFromSfen(sfen: string): Board {
  const parts = sfen.replace(/^sfen /, "").split(" ");
  return { cells: parseBoard(parts[0]), hand: parseHand(parts[2]) };
}

/** Rotate 180° and swap colours, so white's pieces read as black's. */
export function invertBoard(b: Board): Board {
  const cells = [...b.cells].reverse().map((c) => (c ? swapCase(c) : c));
  const hand: Hand = {};
  for (const [k, v] of Object.entries(b.hand)) hand[swapCase(k)] = v;
  return { cells, hand };
}

type Template = { cells: [number, string][]; hand: [string, number][] };
const templateCache = new Map<string, Template>();

function template(t: string): Template {
  let tpl = templateCache.get(t);
  if (!tpl) {
    const [board, hand] = t.split(" ");
    const cells: [number, string][] = [];
    parseBoard(board).forEach((c, i) => c && cells.push([i, c]));
    tpl = { cells, hand: Object.entries(parseHand(hand)) };
    templateCache.set(t, tpl);
  }
  return tpl;
}

export function evalExpr(e: RuleExpr, b: Board): boolean {
  if ("all" in e) {
    const t = template(e.all);
    return (
      t.cells.every(([i, p]) => b.cells[i] === p) && t.hand.every(([k, n]) => (b.hand[k] ?? 0) === n)
    );
  }
  if ("any" in e) {
    return template(e.any).cells.some(([i, p]) => b.cells[i] === p);
  }
  if ("empty" in e) {
    return template(e.empty).cells.every(([i]) => b.cells[i] === "");
  }
  if ("and" in e) return e.and.every((x) => evalExpr(x, b));
  if ("or" in e) return e.or.some((x) => evalExpr(x, b));
  return !evalExpr(e.not, b);
}

export const rules: Rule[] = (rulesJson as Rule[]).slice().sort((a, b) => a.priority - b.priority);
const byGroup = (g: RuleGroup) => rules.filter((r) => r.group === g);
const castleRules = byGroup("castle");
const openingRules = byGroup("opening");
const sideOpeningRules = byGroup("opening_side");
const tacticRules = byGroup("tactic");
const blackTacticRules = byGroup("tactic_black");
const whiteTacticRules = byGroup("tactic_white");

function firstHit(rs: Rule[], b: Board, ply: number): Rule | undefined {
  return rs.find((r) => (r.plyMax === undefined || ply <= r.plyMax) && evalExpr(r.expr, b));
}

/** Files 5–9 on the rook's own side mean the rook swung (from black's view, row-major index). */
function rookSwung(b: Board): boolean {
  for (let row = 5; row < 9; row++) {
    for (let col = 0; col < 5; col++) {
      if (b.cells[row * 9 + col] === "R") return true;
    }
  }
  return false;
}

/**
 * Classify a game from the SFEN after every ply. `sfens[0]` is the initial
 * position, `sfens[i]` the position after ply i.
 */
export function classify(sfens: string[]): Classification {
  const result: Classification = {
    opening: null,
    sideOpening: { black: null, white: null },
    style: { black: "居飛車", white: "居飛車" },
    castles: { black: [], white: [] },
    mainCastle: { black: "", white: "" },
    tactics: { black: [], white: [] },
  };
  const current: Record<Side, string> = { black: "", white: "" };
  const seenTactics: Record<Side, Set<string>> = { black: new Set(), white: new Set() };
  const initialColor = sfens[0]?.split(" ")[1] === "w" ? "white" : "black";

  for (let ply = 1; ply < sfens.length; ply++) {
    const abs = boardFromSfen(sfens[ply]);
    // The side that just moved.
    const side: Side = (ply % 2 === 1) === (initialColor === "black") ? "black" : "white";
    const self = side === "black" ? abs : invertBoard(abs);

    if (!result.opening) {
      const hit = firstHit(openingRules, abs, ply);
      if (hit) {
        result.opening = { name: hit.name, ply };
      } else if (!result.sideOpening[side]) {
        const s = firstHit(sideOpeningRules, self, ply);
        if (s) result.sideOpening[side] = { name: s.name, ply };
      }
    }

    if (ply <= 40 && rookSwung(self)) result.style[side] = "振り飛車";

    const tacticHits = [
      ...(side === "black" ? blackTacticRules : whiteTacticRules).filter(
        (r) => (r.plyMax === undefined || ply <= r.plyMax) && evalExpr(r.expr, abs),
      ),
      ...tacticRules.filter((r) => (r.plyMax === undefined || ply <= r.plyMax) && evalExpr(r.expr, self)),
    ];
    for (const r of tacticHits) {
      if (!seenTactics[side].has(r.name)) {
        seenTactics[side].add(r.name);
        result.tactics[side].push({ name: r.name, ply });
      }
    }

    const castle = firstHit(castleRules, self, ply)?.name ?? "";
    if (castle && castle !== current[side]) {
      current[side] = castle;
      result.castles[side].push({ name: castle, ply });
    }
  }

  for (const side of ["black", "white"] as Side[]) {
    const early = result.castles[side].filter((c) => c.ply <= 60);
    result.mainCastle[side] = (early.at(-1) ?? result.castles[side][0])?.name ?? "";
  }
  return result;
}

/** One-line 戦型 label for the library table, e.g. "四間飛車 vs 居飛車" or "角換わり". */
export function strategyLabel(c: Classification): string {
  if (c.opening) return c.opening.name;
  const b = c.sideOpening.black?.name ?? c.style.black;
  const w = c.sideOpening.white?.name ?? c.style.white;
  if (b === "居飛車" && w === "居飛車") return "相居飛車";
  return `${b} vs ${w}`;
}

/** Coarse split for stats: 相居飛車 / 対抗形 / 相振り飛車. */
export function styleMatchup(c: Classification): "相居飛車" | "対抗形" | "相振り飛車" {
  const { black, white } = c.style;
  if (black === white) return black === "居飛車" ? "相居飛車" : "相振り飛車";
  return "対抗形";
}
